config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-lime-iguana.sh
        container: qc.acc_surly-razzmatazz-cat
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-aqua-zebu.sh
        container: qc.doc_ugly-russet-collie
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-tangerine-mandrill.sh
        container: qc.doc_goopy-brown-frog
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-pink-zebu.sh
        container: qc.doc_messy-gamboge-tortoise
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-rust-grouse.sh
        container: qc.doc_snippy-vermilion-uakari
  QC.FAIR:
    repos:
      github.com/grycap/im F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-harlequin-caracal.sh
        container: qc.fair_frumpy-rose-saola
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-olivine-mongrel.sh
        container: qc.lic_flimsy-bistre-quokka
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-teal-angelfish.sh
        container: qc.met_crabby-scarlet-swan
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cyan-whale.sh
        container: qc.sec_cheeky-wheat-yak
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-persimmon-tuatara.sh
        container: qc.sty_cranky-firebrick-barb
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cerise-newfoundland.sh
        container: qc.ver_nippy-maroon-russel
timeout: 1800
