config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-peach-alligator.sh
        container: qc.acc_stinky-eggplant-bonobo
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cerulean-walrus.sh
        container: qc.doc_stinky-sapphire-mandrill
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-gamboge-cuttlefish.sh
        container: qc.doc_sunny-lemon-booby
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-zucchini-camel.sh
        container: qc.doc_pokey-smalt-albatross
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-sangria-dingo.sh
        container: qc.doc_greasy-sangria-boar
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-platinum-termite.sh
        container: qc.lic_greasy-green-bulldog
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-buff-dugong.sh
        container: qc.met_tacky-chestnut-mouse
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-magnolia-rat.sh
        container: qc.sec_foggy-wheat-zonkey
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-mauve-boar.sh
        container: qc.sty_hasty-carmine-gorilla
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-amaranth-gorilla.sh
        container: qc.sty_nippy-sangria-monkey
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-linen-alligator.sh
        container: qc.sty_silly-denim-bat
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-magnolia-lemur.sh
        container: qc.sty_skinny-taupe-terrier
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-sepia-dog.sh
        container: qc.sty_flimsy-denim-moth
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-ecru-eleuth.sh
        container: qc.ver_cloudy-chartreuse-baboon
timeout: 1800
