config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-plum-woodlouse.sh
        container: qc.acc_squeaky-sapphire-guppy
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-asparagus-cow.sh
        container: qc.doc_wimpy-indigo-bat
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-salmon-dodo.sh
        container: qc.doc_wiggy-cinnabar-capybara
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-olivine-maltese.sh
        container: qc.doc_lumpy-champagne-slug
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-charcoal-ibis.sh
        container: qc.doc_nerdy-wheat-uakari
  QC.FAIR:
    repos:
      github.com/grycap/im F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-burgundy-moorhen.sh
        container: qc.fair_geeky-pumpkin-hare
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-gold-mouse.sh
        container: qc.lic_fuzzy-crimson-forest
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-razzmatazz-gharial.sh
        container: qc.met_jumpy-magenta-frog
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cobalt-greyhound.sh
        container: qc.sec_chewy-tan-quoll
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-indigo-deer.sh
        container: qc.sty_clammy-ivory-capuchin
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-scarlet-donkey.sh
        container: qc.ver_geeky-alizarin-seal
timeout: 1800
