config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-emerald-monster.sh
        container: qc.acc_hazy-grey-catfish
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-maroon-kingfisher.sh
        container: qc.doc_crappy-teal-chow
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-eggplant-coati.sh
        container: qc.doc_goopy-flax-caiman
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-azure-tiger.sh
        container: qc.doc_skimpy-ecru-dog
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-platinum-lion.sh
        container: qc.doc_stinky-ultramarine-cheetah
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-emerald-badger.sh
        container: qc.lic_snappy-maroon-hedgehog
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.ready-saffron-tarsier.sh
        container: qc.met_shaky-zucchini-grasshopper
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-indigo-ostrich.sh
        container: qc.sec_pokey-plum-wrasse
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-magenta-hippopotamus.sh
        container: qc.sty_sickly-russet-uguisu
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-beige-tzu.sh
        container: qc.sty_shaggy-cerise-civet
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-thistle-macaw.sh
        container: qc.sty_geeky-gamboge-heron
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-saffron-bracke.sh
        container: qc.sty_gloppy-lemon-uakari
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-gold-antelope.sh
        container: qc.ver_hazy-khaki-goat
timeout: 1800
