config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-beige-yak.sh
        container: qc.acc_breezy-lime-stoat
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-ruby-crocodile.sh
        container: qc.doc_baggy-azure-lemming
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-smalt-kakapo.sh
        container: qc.doc_surly-cerulean-malamute
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-yellow-toucan.sh
        container: qc.doc_messy-yellow-bandicoot
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cerise-emu.sh
        container: qc.doc_gimpy-thistle-discus
  QC.FAIR:
    repos:
      github.com/grycap/im F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-persimmon-alligator.sh
        container: qc.fair_wheezy-brown-tarsier
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-ruby-dormouse.sh
        container: qc.lic_gamy-magnolia-hummingbird
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-peach-mau.sh
        container: qc.met_muzzy-harlequin-audemer
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-firebrick-barnacle.sh
        container: qc.sec_whiny-tomato-terrier
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-taupe-fly.sh
        container: qc.sty_breezy-turquoise-koala
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-yellow-cuscus.sh
        container: qc.ver_smelly-chartreuse-quoll
timeout: 1800
