config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-brass-millipede.sh
        container: qc.acc_foggy-chartreuse-harrier
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-wheat-boar.sh
        container: qc.doc_surly-maroon-retriever
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-magenta-bee.sh
        container: qc.doc_scummy-grey-koala
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cobalt-echidna.sh
        container: qc.doc_crabby-alizarin-lobster
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-green-opossum.sh
        container: qc.doc_gimpy-khaki-bobcat
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cobalt-cockroach.sh
        container: qc.lic_breezy-apricot-retriever
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-heliotrope-otter.sh
        container: qc.met_wiggy-periwinkle-oriole
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-magenta-badger.sh
        container: qc.sec_wheezy-tan-jackal
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-rose-pinscher.sh
        container: qc.sty_lovely-purple-bear
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-amethyst-heron.sh
        container: qc.sty_cheeky-saffron-butterfly
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-salmon-uakari.sh
        container: qc.sty_hilly-wheat-dunker
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-lilac-olm.sh
        container: qc.sty_snazzy-magnolia-pig
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-orchid-coral.sh
        container: qc.sty_stinky-zucchini-jackal
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-grey-mandrill.sh
        container: qc.ver_fuzzy-tangerine-hornet
timeout: 1800
