config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-lime-guppy.sh
        container: qc.acc_scaly-charcoal-husky
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-azure-buzzard.sh
        container: qc.doc_crabby-aqua-barracuda
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-thistle-bordeaux.sh
        container: qc.doc_stuffy-cerise-wolverine
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-thistle-jellyfish.sh
        container: qc.doc_wheezy-beige-monster
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cerulean-manatee.sh
        container: qc.doc_muzzy-amethyst-fox
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-wisteria-shrew.sh
        container: qc.lic_slimy-cinnamon-squid
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-cinnamon-anteater.sh
        container: qc.met_hazy-mauve-bat
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-corn-chameleon.sh
        container: qc.sec_goopy-copper-butterfly
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-azure-bat.sh
        container: qc.sty_nerdy-copper-rabbit
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-persimmon-fossa.sh
        container: qc.sty_beady-malachite-bear
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-copper-mau.sh
        container: qc.sty_pretty-cornflower-yak
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-chestnut-dog.sh
        container: qc.sty_shaky-tan-chameleon
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-tangerine-ladybird.sh
        container: qc.sty_scanty-bistre-manatee
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-yellow-leopard.sh
        container: qc.ver_shabby-dandelion-mule
timeout: 1800
