config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-orange-emu.sh
        container: qc.acc_slimy-pumpkin-gar
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-khaki-akita.sh
        container: qc.doc_beady-brown-zebra
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-sepia-devil.sh
        container: qc.doc_surly-bistre-audemer
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-periwinkle-bracke.sh
        container: qc.doc_sleazy-vermilion-hyrax
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-silver-husky.sh
        container: qc.doc_shaggy-ivory-frise
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-peach-bobcat.sh
        container: qc.lic_leaky-olive-tuatara
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-russet-squid.sh
        container: qc.met_freaky-ivory-fowl
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-chocolate-moth.sh
        container: qc.sec_chummy-plum-ant
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cornflower-tang.sh
        container: qc.sty_chewy-magnolia-hummingbird
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.homely-copper-quokka.sh
        container: qc.sty_queasy-gold-stingray
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-chartreuse-burmese.sh
        container: qc.sty_snazzy-taupe-cichlid
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-brass-albatross.sh
        container: qc.sty_lanky-wheat-binturong
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-yellow-grouse.sh
        container: qc.ver_chummy-grey-giraffe
timeout: 1800
