config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-goldenrod-rhinoceros.sh
        container: qc.acc_pasty-black-kakapo
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-linen-bullfrog.sh
        container: qc.doc_sleepy-linen-barnacle
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cream-wallaby.sh
        container: qc.doc_queasy-brass-newfoundland
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-ecru-dachsbracke.sh
        container: qc.doc_scummy-ecru-bonobo
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-thistle-oyster.sh
        container: qc.doc_wimpy-denim-antelope
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-teal-vole.sh
        container: qc.lic_grumpy-persimmon-turtle
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-saffron-ocelot.sh
        container: qc.met_scaly-ecru-pig
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-carmine-tarantula.sh
        container: qc.sec_ugly-emerald-bordeaux
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-myrtle-armadillo.sh
        container: qc.sty_sleazy-rust-wallaby
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-rose-hamster.sh
        container: qc.ver_skinny-champagne-urchin
timeout: 1800
