config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-tan-quoll.sh
        container: qc.acc_squirrely-goldenrod-termite
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-gamboge-cockroach.sh
        container: qc.doc_foggy-cyan-gopher
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-jade-bonobo.sh
        container: qc.doc_seedy-tomato-coyote
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-taupe-sloth.sh
        container: qc.doc_stuffy-magnolia-sheepdog
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-ochre-mouse.sh
        container: qc.doc_homely-olive-penguin
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-chestnut-flamingo.sh
        container: qc.lic_sloppy-gold-cockroach
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-lilac-eel.sh
        container: qc.met_paltry-auburn-gharial
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-charcoal-horse.sh
        container: qc.sec_gummy-red-dachsbracke
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-tomato-walrus.sh
        container: qc.sty_scummy-pumpkin-goose
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-heliotrope-starfish.sh
        container: qc.sty_snappy-amaranth-rhinoceros
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-flax-caiman.sh
        container: qc.sty_tacky-beige-hound
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-myrtle-sponge.sh
        container: qc.sty_zippy-harlequin-kakapo
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-pumpkin-barnacle.sh
        container: qc.sty_frumpy-lavender-lobster
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-amber-collie.sh
        container: qc.ver_droopy-tan-whippet
timeout: 1800
