config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-yellow-lynx.sh
        container: qc.acc_wheezy-pumpkin-yak
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-aqua-maltese.sh
        container: qc.doc_hasty-razzmatazz-russel
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-corn-dodo.sh
        container: qc.doc_squeaky-beige-ray
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-teal-abyssinian.sh
        container: qc.doc_hazy-scarlet-spaniel
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-carmine-llama.sh
        container: qc.doc_baggy-malachite-orangutan
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-sepia-fox.sh
        container: qc.lic_smelly-razzmatazz-barnacle
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-black-monster.sh
        container: qc.met_flabby-salmon-buzzard
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-blue-coyote.sh
        container: qc.sec_gimpy-amethyst-mayfly
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-rust-grouse.sh
        container: qc.sty_gimpy-ruby-argentino
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-celadon-javanese.sh
        container: qc.sty_nippy-cardinal-snail
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-violet-bullfrog.sh
        container: qc.sty_ready-denim-dachsbracke
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-red-kingfisher.sh
        container: qc.sty_lovely-jade-serval
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-gamboge-sheepdog.sh
        container: qc.sty_crabby-smalt-flounder
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-plum-schnauzer.sh
        container: qc.ver_greasy-pear-lionfish
timeout: 1800
