config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-bistre-caterpillar.sh
        container: qc.acc_chewy-saffron-birman
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-buff-fox.sh
        container: qc.doc_stuffy-dandelion-gharial
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cinnabar-corgi.sh
        container: qc.doc_seedy-tan-heron
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-black-tiger.sh
        container: qc.doc_scummy-periwinkle-orangutan
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-magnolia-centipede.sh
        container: qc.doc_foggy-champagne-stoat
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-fuchsia-uakari.sh
        container: qc.lic_slaphappy-flax-russel
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.beady-goldenrod-mongrel.sh
        container: qc.met_cozy-tan-newt
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-myrtle-hedgehog.sh
        container: qc.sec_nerdy-teal-spoonbill
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-rose-reindeer.sh
        container: qc.sty_dorky-buff-termite
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-linen-barb.sh
        container: qc.sty_flabby-ultramarine-labradoodle
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-sangria-eleuth.sh
        container: qc.sty_baggy-harlequin-albatross
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-peach-quokka.sh
        container: qc.sty_clammy-olive-stoat
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-khaki-seal.sh
        container: qc.sty_freaky-seashell-gibbon
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-cobalt-anteater.sh
        container: qc.ver_gloppy-goldenrod-swan
timeout: 1800
