config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-olive-chinchilla.sh
        container: qc.acc_clammy-cerulean-tapir
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-peach-camel.sh
        container: qc.doc_randy-taupe-okapi
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-goldenrod-jaguar.sh
        container: qc.doc_skimpy-zucchini-bonobo
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-seashell-barb.sh
        container: qc.doc_squeaky-turquoise-bombay
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-flax-bloodhound.sh
        container: qc.doc_pokey-cinnamon-ibis
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-lilac-uakari.sh
        container: qc.lic_squeaky-flax-sheep
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-russet-turtle.sh
        container: qc.met_randy-rose-frog
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cerulean-urchin.sh
        container: qc.sec_cranky-malachite-ibis
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-bronze-owl.sh
        container: qc.sty_flimsy-yellow-cockroach
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-tan-mammoth.sh
        container: qc.ver_blurry-olive-mole
timeout: 1800
