config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-mauve-dormouse.sh
        container: qc.acc_sickly-bistre-zebu
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-sepia-husky.sh
        container: qc.doc_chummy-celadon-abyssinian
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-celadon-dormouse.sh
        container: qc.doc_stinky-magnolia-falcon
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-magenta-tapir.sh
        container: qc.doc_tasty-sangria-seahorse
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-lilac-quetzal.sh
        container: qc.doc_snazzy-carmine-rattlesnake
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-heliotrope-argentino.sh
        container: qc.lic_fuzzy-rust-mole
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-bistre-beetle.sh
        container: qc.met_lumpy-cobalt-owl
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-khaki-lobster.sh
        container: qc.sec_randy-carmine-wallaby
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-periwinkle-peccary.sh
        container: qc.sty_smelly-fuchsia-bison
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sepia-seal.sh
        container: qc.ver_freaky-rust-blue
timeout: 1800
