config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-platinum-newfoundland.sh
        container: qc.acc_scanty-periwinkle-gorilla
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-celadon-ibis.sh
        container: qc.doc_slaphappy-sepia-neanderthal
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-harlequin-beaver.sh
        container: qc.doc_snippy-emerald-spider
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cinnabar-fousek.sh
        container: qc.doc_shaky-lime-grasshopper
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-yellow-collie.sh
        container: qc.doc_ugly-ochre-falcon
  QC.FAIR:
    repos:
      github.com/grycap/im F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cerulean-squirrel.sh
        container: qc.fair_pasty-jade-meerkat
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-scarlet-pig.sh
        container: qc.lic_wheezy-heliotrope-dog
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-thistle-gorilla.sh
        container: qc.met_hasty-khaki-stoat
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-gamboge-mandrill.sh
        container: qc.sec_leaky-magnolia-lemming
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-khaki-zebra.sh
        container: qc.sty_sleazy-white-tapir
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-rose-blue.sh
        container: qc.ver_dorky-tan-impala
timeout: 1800
