config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-scarlet-molly.sh
        container: qc.acc_homey-cinnabar-havanese
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-eggplant-spider.sh
        container: qc.doc_tacky-cinnamon-jackal
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-brown-gecko.sh
        container: qc.doc_flaky-aquamarine-slug
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-flax-camel.sh
        container: qc.doc_hasty-carmine-millipede
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-maroon-giraffe.sh
        container: qc.doc_cranky-tangerine-burmese
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-brass-albatross.sh
        container: qc.lic_slaphappy-cerise-chinchilla
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-copper-dragonfly.sh
        container: qc.met_gloppy-lime-zebra
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-corn-nightingale.sh
        container: qc.sec_gloppy-chartreuse-hummingbird
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cinnabar-fossa.sh
        container: qc.sty_queasy-chartreuse-cassowary
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-bistre-ferret.sh
        container: qc.sty_randy-amethyst-capuchin
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-lime-audemer.sh
        container: qc.sty_sloppy-wisteria-russel
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.messy-razzmatazz-whippet.sh
        container: qc.sty_snippy-linen-ibis
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-sepia-cow.sh
        container: qc.ver_geeky-indigo-husky
timeout: 1800
