config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-brown-clam.sh
        container: qc.acc_dorky-denim-tetra
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-plum-dalmatian.sh
        container: qc.doc_zippy-xanthic-lemur
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-peach-forest.sh
        container: qc.doc_muzzy-persimmon-tetra
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-mauve-javanese.sh
        container: qc.doc_woolly-heliotrope-devil
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-taupe-cuttlefish.sh
        container: qc.doc_boozy-sangria-gecko
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-goldenrod-whippet.sh
        container: qc.lic_freaky-burgundy-schnauzer
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.homely-thistle-giraffe.sh
        container: qc.met_cloudy-charcoal-quetzal
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-scarlet-eel.sh
        container: qc.sec_zippy-plum-manatee
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cinnabar-dragon.sh
        container: qc.sty_scummy-bistre-donkey
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-linen-buzzard.sh
        container: qc.sty_lousy-linen-lemur
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-bronze-blue.sh
        container: qc.sty_gloppy-rose-cheetah
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-ultramarine-hippopotamus.sh
        container: qc.sty_scaly-ruby-saola
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-buff-stoat.sh
        container: qc.ver_gimpy-brass-devil
timeout: 1800
