config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-sapphire-wolf.sh
        container: qc.acc_tacky-corn-monster
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-rust-akbash.sh
        container: qc.doc_pretty-flax-balinese
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-olivine-gibbon.sh
        container: qc.doc_beady-mauve-chow
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-sepia-macaw.sh
        container: qc.doc_cheeky-orchid-ocelot
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-burgundy-nightingale.sh
        container: qc.doc_sickly-chestnut-mouse
  QC.FAIR:
    repos:
      github.com/grycap/im F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-goldenrod-crab.sh
        container: qc.fair_surly-mauve-stoat
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-carmine-lemur.sh
        container: qc.lic_gummy-salmon-impala
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-cinnabar-hyena.sh
        container: qc.met_gimpy-persimmon-mastiff
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-orchid-frog.sh
        container: qc.sec_cranky-cerulean-whale
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-burgundy-barracuda.sh
        container: qc.sty_skanky-salmon-drever
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-taupe-lion.sh
        container: qc.ver_paltry-russet-shrimp
timeout: 1800
