config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cinnamon-forest.sh
        container: qc.acc_snoopy-smalt-goose
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-xanthic-manatee.sh
        container: qc.doc_thirsty-burgundy-newt
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-denim-uakari.sh
        container: qc.doc_shaggy-wheat-bonobo
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-linen-hyena.sh
        container: qc.doc_sloppy-brass-spaniel
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cinnabar-wolfhound.sh
        container: qc.doc_goopy-smalt-woodlouse
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-olive-setter.sh
        container: qc.lic_trippy-buff-chinook
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-magenta-zebu.sh
        container: qc.met_scummy-crimson-dormouse
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-russet-bordeaux.sh
        container: qc.sec_scaly-turquoise-javanese
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-goldenrod-caiman.sh
        container: qc.sty_woolly-xanthic-akita
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-burgundy-flounder.sh
        container: qc.sty_ready-orchid-wolf
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-pink-panda.sh
        container: qc.sty_homely-ruby-robin
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-silver-quail.sh
        container: qc.ver_boozy-platinum-seahorse
timeout: 1800
