config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-wisteria-kakapo.sh
        container: qc.acc_homely-gold-angora
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-peach-okapi.sh
        container: qc.doc_cloudy-white-bird
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-asparagus-cheetah.sh
        container: qc.doc_woozy-salmon-collie
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-rust-coati.sh
        container: qc.doc_messy-gold-neanderthal
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-orange-liger.sh
        container: qc.doc_muzzy-violet-buzzard
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-mustard-affenpinscher.sh
        container: qc.lic_snazzy-aquamarine-abyssinian
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-silver-millipede.sh
        container: qc.met_nerdy-razzmatazz-kakapo
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-orange-hound.sh
        container: qc.sec_scanty-scarlet-urchin
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-champagne-shrimp.sh
        container: qc.sty_snappy-fuchsia-skunk
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-black-akbash.sh
        container: qc.sty_crabby-viridian-moose
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-pear-molly.sh
        container: qc.sty_paltry-ecru-barnacle
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-chestnut-dhole.sh
        container: qc.sty_flimsy-alizarin-manatee
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-celadon-cattle.sh
        container: qc.sty_nippy-auburn-caterpillar
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-olive-affenpinscher.sh
        container: qc.ver_skanky-teal-moorhen
timeout: 1800
