config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-cinnamon-havanese.sh
        container: qc.acc_goopy-yellow-worm
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cobalt-audemer.sh
        container: qc.doc_snippy-purple-fly
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-ochre-emu.sh
        container: qc.doc_seedy-turquoise-slug
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-persimmon-shrimp.sh
        container: qc.doc_skimpy-denim-sheepdog
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-myrtle-malamute.sh
        container: qc.doc_lovely-brown-duck
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cardinal-greyhound.sh
        container: qc.lic_thirsty-ochre-squirrel
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-ultramarine-hippopotamus.sh
        container: qc.met_lumpy-cardinal-kakapo
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-mustard-moth.sh
        container: qc.sec_tacky-ruby-cattle
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-gold-coyote.sh
        container: qc.sty_frumpy-crimson-discus
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-gold-manatee.sh
        container: qc.ver_lousy-lime-tang
timeout: 1800
