config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cinnamon-fox.sh
        container: qc.acc_shabby-violet-antelope
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cobalt-ragdoll.sh
        container: qc.doc_stuffy-copper-javanese
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-bronze-owl.sh
        container: qc.doc_snappy-sangria-dormouse
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-fuchsia-uguisu.sh
        container: qc.doc_ready-maroon-boar
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-alizarin-paradise.sh
        container: qc.doc_grumpy-tangerine-dogfish
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-amethyst-mongrel.sh
        container: qc.lic_flabby-celadon-olm
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-ruby-raccoon.sh
        container: qc.met_gloppy-malachite-mongoose
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-brass-panda.sh
        container: qc.sec_woozy-malachite-ostrich
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cardinal-whippet.sh
        container: qc.sty_bluesy-burgundy-chihuahua
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-champagne-donkey.sh
        container: qc.sty_dorky-olivine-corgi
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-taupe-reindeer.sh
        container: qc.sty_hasty-crimson-caracal
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-rose-chipmunk.sh
        container: qc.ver_stinky-cardinal-moose
timeout: 1800
