config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-black-uguisu.sh
        container: qc.acc_greasy-apricot-bracke
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-linen-peccary.sh
        container: qc.doc_freaky-champagne-cichlid
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-silver-dolphin.sh
        container: qc.doc_muggy-cardinal-pinscher
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-aqua-fox.sh
        container: qc.doc_muggy-amethyst-quokka
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-corn-nightingale.sh
        container: qc.doc_pasty-smalt-bulldog
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-sepia-buffalo.sh
        container: qc.lic_leaky-heliotrope-spaniel
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-thistle-otter.sh
        container: qc.met_shaggy-rust-bear
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-salmon-spoonbill.sh
        container: qc.sec_crappy-lime-cassowary
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-teal-tetra.sh
        container: qc.sty_queasy-gamboge-fowl
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-beige-caterpillar.sh
        container: qc.sty_scaly-rust-deer
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-heliotrope-dodo.sh
        container: qc.sty_hazy-white-mammoth
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-brown-akita.sh
        container: qc.ver_snappy-alizarin-dolphin
timeout: 1800
