config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: master
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-maroon-moorhen.sh
        container: qc.acc_bumpy-myrtle-dolphin
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-aqua-neanderthal.sh
        container: qc.doc_gamy-peach-dogfish
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-denim-stingray.sh
        container: qc.doc_hilly-purple-buzzard
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-celadon-fly.sh
        container: qc.doc_pokey-celadon-bombay
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-persimmon-caiman.sh
        container: qc.doc_crappy-emerald-pig
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cinnamon-dane.sh
        container: qc.lic_queasy-lilac-malamute
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cobalt-scorpion.sh
        container: qc.met_cloudy-wisteria-angora
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-jade-mongoose.sh
        container: qc.sec_snappy-alizarin-fousek
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-champagne-lemming.sh
        container: qc.sty_bumpy-harlequin-dog
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-goldenrod-sponge.sh
        container: qc.sty_snazzy-alizarin-uakari
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-lilac-meerkat.sh
        container: qc.sty_crabby-pumpkin-mouse
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-bronze-leopard.sh
        container: qc.ver_pokey-zucchini-moorhen
timeout: 1800
