config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/grycap/im:
      branch: devel
      repo: https://github.com/grycap/im
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-myrtle-robin.sh
        container: qc.acc_frumpy-russet-bloodhound
  QC.Doc:
    repos:
      github.com/grycap/im find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cinnamon-beagle.sh
        container: qc.doc_homey-champagne-impala
      github.com/grycap/im git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-rose-dachsbracke.sh
        container: qc.doc_skimpy-magenta-russel
      github.com/grycap/im markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-sepia-beaver.sh
        container: qc.doc_beady-brass-zonkey
      github.com/grycap/im restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-jade-beaver.sh
        container: qc.doc_snippy-salmon-hippopotamus
  QC.Lic:
    repos:
      github.com/grycap/im licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-pink-llama.sh
        container: qc.lic_foggy-auburn-hedgehog
  QC.Met:
    repos:
      github.com/grycap/im validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-pink-kudu.sh
        container: qc.met_homely-smalt-bat
  QC.Sec:
    repos:
      github.com/grycap/im bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-tomato-dragonfly.sh
        container: qc.sec_snoopy-jade-walrus
  QC.Sty:
    repos:
      github.com/grycap/im flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-brass-cichlid.sh
        container: qc.sty_homely-tomato-hamster
      github.com/grycap/im hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-viridian-spoonbill.sh
        container: qc.sty_flimsy-denim-monster
      github.com/grycap/im jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-rose-hedgehog.sh
        container: qc.sty_ugly-bistre-beetle
      github.com/grycap/im rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-crimson-goat.sh
        container: qc.sty_randy-olivine-javanese
      github.com/grycap/im stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-silver-ostrich.sh
        container: qc.sty_flaky-peach-worm
  QC.Ver:
    repos:
      github.com/grycap/im get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-auburn-rhinoceros.sh
        container: qc.ver_woolly-coral-swan
timeout: 1800
